
#### 定义
当你需要一个新的错误类型，都可以用 errors（必须先 import）包的 errors.New 函数接收合适的错误信息来创建，像下面这样：
```
err := errors.New("math - square root of negative number")

```

#### panic
panic 可以直接从代码初始化：当错误条件（我们所测试的代码）很严苛且不可恢复，程序不能继续运行时，可以使用 panic 函数产生一个中止程序的运行时错误。panic 接收一个做任意类型的参数，通常是字符串，在程序死亡时被打印出来。Go 运行时负责中止程序并给出调试信息。在示例 13.2 panic.go 中阐明了它的工作方式：
```
package main

import "fmt"

func main() {
    fmt.Println("Starting the program")
    panic("A severe error occurred: stopping the program!")
    fmt.Println("Ending the program")
}

```


#### recover 

recover 只能在 defer 修饰的函数中使用：用于取得 panic 调用中传递过来的错误值，如果是正常执行，调用 recover 会返回 nil，且没有其它效果。

总结：panic 会导致栈被展开直到 defer 修饰的 recover() 被调用或者程序中止。

```
package main

import "fmt"

func badCall(){
	panic("bad end")
}

func test(){
	defer func(){
		if e := recover(); e != nil {
			fmt.Printf("Panicing %s \r\n" , e)
		}
	}()
	badCall()
	fmt.Printf("After bad call \r\n")
}


func main() {
	fmt.Println("Calling")
	test()
	fmt.Println("test completed")
}


```








